services:
  api1:
    image: rodscaldeira/rinha2026:0.0.5
    hostname: api1
    environment:
      SOCKET: /sockets/api1.sock
    healthcheck:
      test: ["CMD-SHELL", "curl -sf --unix-socket /sockets/api1.sock http://localhost/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "155M"
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    image: rodscaldeira/rinha2026:0.0.5
    hostname: api2
    environment:
      SOCKET: /sockets/api2.sock
    healthcheck:
      test: ["CMD-SHELL", "curl -sf --unix-socket /sockets/api2.sock http://localhost/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "155M"
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  lb:
    image: haproxy:3.1-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  sockets:
